spring:
  application:
    name: sb04_oracle_mybatis_thymeleaf
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: scott
    password: tiger
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 80
#mybatis
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml