spring:
  application:
    name: sb05_oracle_jpa_thymeleaf

server:
  port: 80
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true